### ISSUE TITLE
Правки до ДЗ 21

### ISSUE THREAD

**Issue by Dexter19** [TooMuchSoulless/TooMuchSoulless.github.io#1]
12.Видалити елементи 'Catwoman' і 'Joker' з масиву names:
Використаємо краще метод splice().
const names = ['Batman', 'Catwoman', 'Joker', 'Bane'];
names.splice(1, 2);
----------------------------------

**Comment by TooMuchSoulless** [comment]
Справді, так набагато простіше вийшло) Виправила) Дякую!
