### ISSUE TITLE
Правки до ДЗ 22

### ISSUE THREAD

**Issue by Dexter19** [TooMuchSoulless/TooMuchSoulless.github.io#2]
4.Отримати третій абзац за допомогою document.querySelector('#id') за його ідентифікатором p3. Призначити для нього клас third
Можна написати код набагато простіше:
const p3 = document.getElementById('p3');
p3.className = "third";
----------------------------------

**Comment by TooMuchSoulless** [comment]
Чудовий варіант) Виправила, дякую!
